# Generated by Django 3.2.4 on 2021-09-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_category_comment_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default='New York', max_length=200),
            preserve_default=False,
        ),
    ]
