# Generated by Django 3.2.4 on 2021-09-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_item_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='winner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
