# Generated by Django 3.2.4 on 2021-09-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_item_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bidder',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
