# Generated by Django 3.2.4 on 2021-09-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to='auctions.Item'),
        ),
    ]
