# Generated by Django 3.2.4 on 2022-03-24 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_bid_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bid', to='auctions.item'),
        ),
    ]
